let numero = 7;
//console.log(numero * 1);
//console.log(numero * 2);
//console.log(numero * 3);
//console.log(numero * 4);
//console.log(numero * 5);
//console.log(numero * 6);
//console.log(numero * 7);
//console.log(numero * 8);
//console.log(numero * 9);
//for(let contador = 1; contador <= 9; contador += 1) {
  //  console.log(numero * contador);
//}
//let listaDeNomes = ['Joana', 'Maria', 'Lucas'];
//for(let indice = 0; indice < listaDeNomes.length; indice++) {
  //  let mensagem = 'Boas vindas, ' + listaDeNomes[indice] + '!'
  //  console.log(mensagem);
//}

let cars = ['Saab', 'Volvo', 'BMW'];
//let cars = ['Saab', 'Volvo', 'BMW'];
//console.log(cars[0]); // Saab
//console.log(cars[1]); // Volvo
//console.log(cars[2]); // BMW
//let cars = ["Saab", "Volvo", "BMW"];

for (let index = 0; index < cars.length; index += 1) {
  console.log(cars[index]);
}

let groceryList = ['Arroz', 'Feijão', 'Alface', 'Melancia'];
for(let vital = 0; vital < groceryList.length; vital ++) {
    const pratoPrincipal = groceryList[vital];
    console.log(pratoPrincipal);
}